[package]
name = "stl"
version = "0.0.1"
edition = "2021"
description = "Rust implementation of STL with indices"
repository = "https://github.com/RishabhRD/rs-stl"

[dependencies]
rayon-core = "1.13.0"

[patch.crates-io.crossbeam-epoch]
git = "https://github.com/crossbeam-rs/crossbeam"
rev = "6ddfad6846ec4493c5f28c78e7dbfd97603e0ebc"

[patch.crates-io.crossbeam-utils]
git = "https://github.com/crossbeam-rs/crossbeam"
rev = "6ddfad6846ec4493c5f28c78e7dbfd97603e0ebc"
