[package]
name = "stl"
version = "0.0.1"
edition = "2021"
description = "Rust implementation of STL with indices"
repository = "https://github.com/RishabhRD/rs-stl"

[dependencies]
rayon-core = "1.13.0"
